# Day 1: Pandas Basics (with NumPy comparison)

Topics: Series, DataFrame, inspecting data, reading and writing CSV, Pandas vs NumPy.

## 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
print(pd.__version__)

3.0.2

## 2. Series (1-D labelled data)

In [2]:
s = pd.Series([85, 92, 78], index=["Asha", "Ravi", "Meena"])
print(s)

Asha     85
Ravi     92
Meena    78
dtype: int64

## 3. DataFrame (2-D table)

In [3]:
data = {
    "name":  ["Asha", "Ravi", "Meena", "Kiran", "Divya", "Arjun"],
    "dept":  ["CSE", "ECE", "CSE", "ME", "ECE", "CSE"],
    "city":  ["Bengaluru", "Mysuru", "Bengaluru", "Hubli", "Mysuru", "Mangaluru"],
    "marks": [85, 92, 78, None, 88, 95],
    "age":   [20, 21, 20, 22, 21, 20],
}
df = pd.DataFrame(data)
print(df)

    name dept       city  marks  age
0   Asha  CSE  Bengaluru   85.0   20
1   Ravi  ECE     Mysuru   92.0   21
2  Meena  CSE  Bengaluru   78.0   20
3  Kiran   ME      Hubli    NaN   22
4  Divya  ECE     Mysuru   88.0   21
5  Arjun  CSE  Mangaluru   95.0   20

## 4. Inspect the data

In [4]:
print(df.shape)       # (rows, columns)
print(df.dtypes)      # type of each column
df.info()             # columns, non-null counts, memory

(6, 5)
name         str
dept         str
city         str
marks    float64
age        int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   dept    6 non-null      str
 2   city    6 non-null      str
 3   marks   5 non-null      float64
 4   age     6 non-null      int64
dtypes: float64(1), int64(1), str(3)
memory usage: 372.0 bytes

In [5]:
df.describe()          # count, mean, std, min, quartiles, max (numeric columns)

           marks        age
count   5.000000   6.000000
mean   87.600000  20.666667
std     6.580274   0.816497
min    78.000000  20.000000
25%    85.000000  20.000000
50%    88.000000  20.500000
75%    92.000000  21.000000
max    95.000000  22.000000

## 5. Write and read CSV

In [6]:
df.to_csv("students.csv", index=False)       # write
back = pd.read_csv("students.csv")           # read

In [7]:
back.head()

    name dept       city  marks  age
0   Asha  CSE  Bengaluru   85.0   20
1   Ravi  ECE     Mysuru   92.0   21
2  Meena  CSE  Bengaluru   78.0   20
3  Kiran   ME      Hubli    NaN   22
4  Divya  ECE     Mysuru   88.0   21

## 6. Pandas vs NumPy

NumPy arrays have no labels and one dtype. Pandas adds labels and mixed types.

In [8]:
arr = np.array([[85, 20], [92, 21]])
print(arr)                              # no labels, one dtype
print(df[["marks", "age"]].head(2))     # labels, mixed types possible

[[85 20]
 [92 21]]
   marks  age
0   85.0   20
1   92.0   21

In [9]:
print(df["marks"].to_numpy())           # Pandas -> NumPy
print(np.mean(arr[:, 0]))                # NumPy maths on one column

[85. 92. 78. nan 88. 95.]
88.5